# syntax=docker/dockerfile:1

FROM python:3.8-slim-buster
# FROM python:3.6
WORKDIR /app

COPY machine_python .
RUN pip3 install -r requirements.txt
# CMD [ "python", "mbs"]


# COPY requirements.txt requirements.txt
# CMD [ "python3", "-m" , "flask", "run", "--host=0.0.0.0"]
CMD tail -f /dev/null
